/* tslint:disable */
/* eslint-disable */
/**
 * IWM Backend API
 * Documentation for the modular monolith hexagonal backend APIs.
 *
 * The version of the OpenAPI document: 0.1.0-SNAPSHOT
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

